"""
Django settings for myproject project.

Generated by 'django-admin startproject' using Django 5.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
import os 
from pathlib import Path
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


load_dotenv() # .env 파일 로드

SECRET_KEY = os.environ.get('SECRET_KEY')

# Quick-start development settings - unsuitable for production

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost',
    '127.0.0.1',  # localhost와 같은 의미
    '0.0.0.0',       # Docker 컨테이너의 내부 호스트 주소
    '.ngrok-free.app',  # ngrok v3 주소 허용
    '.ngrok.io',        # 구버전 ngrok 주소 허용
    "http://localhost:3000",
    '134.185.99.4',   #오라클 ip 추가
    ]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # 프로젝트 앱
    'api',
    # 외부 패키지
    'corsheaders',  # CORS 처리를 위한 앱
    'rest_framework', # 요청 제한을 위한 DRF
]

REST_FRAMEWORK = {
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle', 
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/hour', 
    }
}

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # ★ CORS 미들웨어를 최상단에 배치
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'myproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'myproject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# ----------------------------------------------------------------------
# URL 설정 수정: POST 요청에서 슬래시 리다이렉션 오류 방지
# ----------------------------------------------------------------------
APPEND_SLASH = False # 이 줄을 추가하여 자동 슬래시 추가 기능을 비활성화합니다.

# ----------------------------------------------------------------------
# CORS 설정 (프론트엔드 통신 허용)
# ----------------------------------------------------------------------

# 프론트엔드가 실행되는 주소만 명시적으로 허용 (개발 환경 기준)
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:8080",
    "http://134.185.99.4",  # 프론트엔드가 접속할 최종 주소
]

# ngrok을 사용할 경우: ngrok 도메인도 허용
# CORS_ALLOWED_ORIGIN_REGEXES = [
#     r"^https://.*\.ngrok-free\.app$",
#     r"^https://.*\.ngrok\.io$",
# ]

# 개발 목적으로 모든 출처 허용 (보안 취약, 운영 시 절대 사용 금지)
CORS_ALLOW_ALL_ORIGINS = True


CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'ngrok-skip-browser-warning',  # ngrok 관련 헤더 추가
]

# CSRF 보안 설정 (개발 환경에서 임시로 완화)
CSRF_COOKIE_SECURE = False
CSRF_COOKIE_HTTPONLY = False

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'